/*
 * Copyright 2020 SpinalCom - www.spinalcom.com
 *
 * This file is part of SpinalCore.
 *
 * Please read all of the following terms and conditions
 * of the Free Software license Agreement ("Agreement")
 * carefully.
 *
 * This Agreement is a legally binding contract between
 * the Licensee (as defined below) and SpinalCom that
 * sets forth the terms and conditions that govern your
 * use of the Program. By installing and/or using the
 * Program, you agree to abide by all the terms and
 * conditions stated or referenced herein.
 *
 * If you do not agree to abide by these terms and
 * conditions, do not demonstrate your acceptance and do
 * not install or use the Program.
 * You should have received a copy of the license along
 * with this file. If not, see
 * <http://resources.spinalcom.com/licenses.pdf>.
 */

export default {
  Cancel: 'Cancel',
  Confirm: 'Confirm',
  Table: 'Table',
  True: 'True',
  False: 'False',
  Min: 'Minimum',
  Max: 'Maximum',
  Average: 'Average',
  Value: 'Value',
  'sidebar.topButton.buildingNameDefault': 'Building',
  'error.returntodrive.confirmbtntext': 'Retrun to drive',
  'error.returntodrive.text': 'Imposible to load the digital twin.',
  'error.returntodrive.title': 'Error',
  'Routes.AppList': 'ApplicationList',
  'Routes.DataApp': 'Data room',
  'Routes.InsightCenter': 'Insights',
  // 'Routes.SpaceCenter': 'Inspect the spaces',
  'Routes.SpaceApp': 'Spaces',
  'Routes.EquipmentApp': 'Equipments',
  'Routes.TicketApp': 'Tickets',


  'Routes.Application List': 'Application List',
  'Routes.Data room': 'Data room',
  'Routes.Insights': 'Insights',
  'Routes.Equipments': 'Equipments',
  'Routes.Tickets': 'Tickets',
  'Routes.Alarms': 'Alarms',
  'Routes.Spaces': 'Spaces',


 // data room
  'DataRoom.geographicContext': 'Contextes', // Could be generic
  'DataRoom.geographicBuilding': 'Bâtiments', // Could be generic
  'DataRoom.geographicFloor': 'Etages', // Could be generic
  'DataRoom.geographicRoom': 'Locaux', // Could be generic
  'DataRoom.BIMObject': 'Objets', // Could be generic
  'DataRoom.Area': 'Surface',
  'DataRoom.Ticket': 'Tickets',
  'DataRoom.Name': 'Nom',
  'DataRoom.Note': 'Notes',
  'DataRoom.Documentation': 'Documentation',
  'DataRoom.Calendar': 'Calendrier',
  'DataRoom.Equipment': 'Equipements',
  'DataRoom.Attributes': 'Attributes',
  'DataRoom.User': 'Utilisateurs',
  'DataRoom.Priority': 'Priorités',
  'DataRoom.ScreenShot': 'Make a screen shot',
  'DataRoom.PointView': 'Save one point of view',
  'DataRoom.PJ': 'Add attachments',
  'DataRoom.Endpoints': 'Endpoints',
  'DataRoom.Insight': 'Insight',
  'node-type.context': 'Contexts',
  'node-type.groupingCategory': 'Categories',
  'node-type.BIMObjectGroupContext': 'BIM objects groups contexts',
  'node-type.BIMObjectGroup': 'BIM Object Groups',
  'node-type.BIMObject': ' BIM Objects',
  'node-type.geographicContext': 'Geographic contexts',
  'node-type.geographicBuilding': 'Buildings',
  'node-type.geographicFloor': 'Floors',
  'node-type.geographicRoom': 'Rooms',
  'node-type.SpinalSystemServiceTicket': 'Tickets contexts',
  'node-type.SpinalServiceTicketProcess': 'Processes',
  'node-type.SpinalSystemServiceTicketTypeStep': 'Steps',
  'node-type.SpinalSystemServiceTicketTypeTicket': 'Tickets',
  'node-type.hasFiles': 'Documentation',
  'node-type.hasCategoryAttributes': 'Attributes', // TODO replace references for spinal-twin
  'node-type.Sum': 'Count',
  'node-type.Category': 'Category',
  'node-type.Attribute': 'Attribute',
  'spinal-twin.DeleteConfirm': 'Are you sure you want to delete that element ?',
  'spinal-twin.Back': 'Go Back',
  'spinal-twin.Isolate': 'Isolate',
  'spinal-twin.Select': 'Select',
  'spinal-twin.Area': 'Area (m²)',
  'spinal-twin.children': 'Child node number',
  'spinal-twin.Chart' : 'Chart',
  'datas.current-value': "Current values",

  'spinal-twin.BuildingCount': 'Building number',
  'spinal-twin.FloorCount': "Floor number",
  'spinal-twin.RoomCount': 'Room number',

  'sidebar.topButton.buildingNameDefault': 'Building',
  'error.returntodrive.confirmbtntext': 'Retrun to drive',
  'error.returntodrive.text': 'Imposible to load the digital twin.',
  'error.returntodrive.title': 'Error',
  // 'Routes.AppList': 'Select the application',
  // 'Routes.DataApp': 'Explore the building',
  // 'Routes.InsightCenter': 'Visualize the activity',
  // 'Routes.SpaceCenter': 'Inspect the spaces',
  // 'Routes.EquipmentApp': 'Inspect the equipments',
  // 'Routes.TicketApp': 'Handle the tickets',
  'DataRoom.geographicContext': 'Contextes', // Could be generic
  'DataRoom.geographicBuilding': 'Bâtiments', // Could be generic
  'DataRoom.geographicFloor': 'Etages', // Could be generic
  'DataRoom.geographicRoom': 'Locaux', // Could be generic
  'DataRoom.BIMObject': 'Objets', // Could be generic
  'DataRoom.Area': 'Surface',
  'DataRoom.Ticket': 'Tickets',
  'DataRoom.Name': 'Nom',
  'DataRoom.Note': 'Notes',
  'DataRoom.Documentation': 'Documentation',
  'DataRoom.Calendar': 'Calendrier',
  'DataRoom.Equipment': 'Equipements',
  'DataRoom.Attributes': 'Attributes',
  'DataRoom.User': 'Utilisateurs',
  'DataRoom.Priority': 'Priorités',
  'DataRoom.ScreenShot': 'Make a screen shot',
  'DataRoom.PointView': 'Save one point of view',
  'DataRoom.PJ': 'Add attachments',
  'DataRoom.Endpoints': 'Endpoints',
  'DataRoom.Insight': 'Insight',
  'node-type.context': 'Contexts',
  'node-type.groupingCategory': 'Categories',
  'node-type.BIMObjectGroupContext': 'BIM objects groups contexts',
  'node-type.BIMObjectGroup': 'BIM Object Groups',
  'node-type.BIMObject': ' BIM Objects',
  'node-type.geographicContext': 'Geographic contexts',
  'node-type.geographicBuilding': 'Buildings',
  'node-type.geographicFloor': 'Floors',
  'node-type.geographicRoom': 'Rooms',
  'node-type.SpinalSystemServiceTicket': 'Tickets contexts',
  'node-type.SpinalServiceTicketProcess': 'Processes',
  'node-type.SpinalSystemServiceTicketTypeStep': 'Steps',
  'node-type.SpinalSystemServiceTicketTypeTicket': 'Tickets',
  'node-type.hasFiles': 'Documentation',
  'node-type.hasCategoryAttributes': 'Attributes', // TODO replace references for spinal-twin
  'node-type.Sum': 'Count',
  'node-type.Category': 'Category',
  'node-type.Attribute': 'Attribute',
  'node-type.geographicRoomGroupContext': 'Room group contexts',
  'spinal-twin.DeleteConfirm': 'Are you sure you want to delete that element ?',
  'spinal-twin.Back': 'Go Back',
  'spinal-twin.Isolate': 'Isolate',
  'spinal-twin.Select': 'Select',
  'spinal-twin.Area': 'Area (m²)',
  'spinal-twin.children': 'Child node number',
  'node-type.geographicRoomGroup':'Groups',

  'spinal-twin.CategoryCount': 'Category number',
  'spinal-twin.GroupCount': 'Group number',
  'spinal-twin.EquipmentCount': 'Equipment number',
  'spinal-twin.TotalEquipments': 'Total equipment number',

  'spinal-twin.ProcessCount': 'Process number',
  'spinal-twin.StepCount': 'Step number',
  'spinal-twin.TicketCount': 'Ticket number',
  'spinal-twin.TotalTickets': 'Total ticket number',


  'spinal-twin.hasCategoryAttributes': 'Attributes',
  'spinal-twin.CategoryAdd': 'Add attribute category',
  'spinal-twin.CategoryEdit': 'Edit category ',
  'spinal-twin.AttributeEdit': 'Edit attribute ',
  'spinal-twin.AttributeRemove': 'Remove attribute ',
  'spinal-twin.CategoryAddAttribute': 'Add attribute to ',
  'spinal-twin.CategoryEdit': 'Edit categorie ',
  'spinal-twin.CategoryRemove': 'Remove category ',
  'spinal-twin.Explorer': 'Explorer',
  'spinal-twin.Documentation': 'Documentation',
  'spinal-twin.DocumentAdd': 'Add document',
  'spinal-twin.DocumentDownload': 'Download document',
  'spinal-twin.DocumentRemove': 'Remove document',
  'spinal-twin.Notes': 'Notes',
  'spinal-twin.NoteSend': 'Send note',
  'spinal-twin.DeleteNote': 'Delete note',
  'spinal-twin.NoteDownload': 'Download file',
  'spinal-twin.NoteRestore': 'Restore position',
  'spinal-twin.NotesAddPosition': 'Add current position as attachment',
  'spinal-twin.NotesAddScreenshot':
    'Add a screenshot of the viewer as attachment',
  'spinal-twin.NotesAddFile': 'Add file as attachment',
  'spinal-twin.NotesDeleteAttachment': 'Delete attachment',

  'spinal-twin.Tickets': 'Tickets',
  'spinal-twin.TicketAuthor': 'By',
  'spinal-twin.TicketNotes': "Ticket's notes",
  'spinal-twin.TicketInspect': 'Inspect ticket',
  'spinal-twin.TicketArchive': 'Toggle archive ticket',
  'spinal-twin.TicketAdd': 'Adding ticket',
  'spinal-twin.TicketDeclare': 'Declare a ticket',
  'spinal-twin.SelectContext': 'Select a context',
  'spinal-twin.SelectProcess': 'Select a process',
  'spinal-twin.SelectIncident': 'Select an incident or write a title',
  'spinal-twin.TicketPrev': 'Move ticket a step back',
  'spinal-twin.TicketNext': 'Move ticket to the next step',
  'spinal-twin.TicketPriority.Occasion': 'Occasional',
  'spinal-twin.TicketPriority.Normal': 'Normal',
  'spinal-twin.TicketPriority.Urgent': 'Urgent',
  'spinal-twin.Target-parent': 'From',

  'spinal-twin.CurrentStep': 'Current step',
  'spinal-twin.Step': 'Step',
  'spinal-twin.Priority': 'Priority',
  'spinal-twin.Description': 'Description',
  'spinal-twin.CreationTime': 'Created on',
  'spinal-twin.Events': 'Events',
  'spinal-twin.User': 'User',
  'spinal-twin.Calendar': 'Calendar',
  'spinal-twin.EventDelete': 'Delete event',
  'spinal-twin.EventAdd': 'Add an event',

  'spinal-twin.Today': 'Today',
  'spinal-twin.Yesterday': 'Yesterday',
  'spinal-twin.DaysAgo': ' days ago',
  'spinal-twin.StartDate': 'Date de début',
  'spinal-twin.EndDate': 'Date de fin',

  'spinal-twin.ColorSwitch': 'Activate or deactivate colors',
  'spinal-twin.DownloadList': 'Download data as excel',
  'spinal-twin.NextNode': 'Follow this node',
  'spinal-twin.Inspect': 'Inspect this node',

  'spinal-twin.Name': 'Name',
  'spinal-twin.Type': 'Type',
  'spinal-twin.Path': 'Path',
  'spinal-twin.Target': 'On',
  'spinal-twin.Parent': "Target's parent",
  'spinal-twin.Endpoints': 'Endpoints',
  'spinal-twin.ControlEndpoints': 'Insights',
  'spinal-twin.ErrorFileTooLarge':
    'The selected file(s) is too large. The maximum size must not exceed ',
  'explorer.Name': 'Name',
  'SpaceManagement.Nom': 'Name',
  'SpaceManagement.Categories': 'Categories',
  'SpaceManagement.NombreTotalGroupe': 'Total number of groups',
  'SpaceManagement.NombreTotalPiece': 'Total Number of rooms',
  'SpaceManagement.SurfaceTotale': 'Total Area',
  'SpaceManagement.Groupe': 'Group',
  'SpaceManagement.NombreDePiece': 'Number of rooms',
  'SpaceManagement.ListeDePiece': 'List of rooms',
  'SpaceManagement.Surface': 'Area',
  'HeatmapCenter.Contextes': 'Contexts',
  'HeatmapCenter.Nb_groupes': 'Groups',
  'HeatmapCenter.Groupe': 'Group',
  'HeatmapCenter.Categories': 'Categories',
  'HeatmapCenter.Nb_pieces': 'Rooms',
  'HeatmapCenter.Nb_profils': 'Profils',
  'HeatmapCenter.lst_profils': 'List of profils',
  'HeatmapCenter.Surface': 'Area(M²)',
  'HeatmapCenter.Groupes': 'Groups',
  'HeatmapCenter.Indicateurs': 'Indicator',
  'HeatmapCenter.Profil': 'Profil',
  'HeatmapCenter.Valeur': 'Value',
  'HeatmapCenter.Heatmap_bool': 'Display Heatmap',
  'HeatmapCenter.Courbe_bool': 'Display graph',
  'HeatmapCenter.GO': 'Go',
  'HeatmapCenter.ModifyAll': 'Modify all values',
  'HeatmapCenter.no-variable-selected' : 'No data.',
  'HeatmapCenter.visualized-insight' : 'Visualized insight',
  // Alarms
  'Routes.AlarmApp': 'Alarms',
  'spinal-twin.AlarmProcessCount': 'Process count',
  'spinal-twin.TotalAlarms': 'Total Alarm count',
  'spinal-twin.AlarmCount': 'Alarm count',
  'node-type.SpinalSystemServiceTicket.Alarm': 'Alarm contexts',
  'node-type.SpinalServiceTicketProcess.Alarm': 'Alarm Processes',
  'node-type.SpinalSystemServiceTicketTypeStep.Alarm': 'Steps',
  'node-type.SpinalSystemServiceTicketTypeTicket.Alarm': 'Alarms',
  // Dashboard and Chart
  'node-type.close-chart' : 'Back to 3D',
  'spinal-twin.open-in-dataroom' : 'Switch to Data Room',
  'spinal-twin.insight-center.change-value' : 'Change Value',
  'spinal-twin.insight-center.see-historic' : 'Display Historic',
  'spinal-twin.insight-center.download' : 'Download Datas',
  'spinal-twin.insight-center.display-sprites' : 'Display as sprites',
  'spinal-twin.Inventory' : 'Inventory',
  'spinal-twin.Inventory-tab.space-inventory' : 'SPACE INVENTORY',
  // 'spinal-twin.SpaceConfiguration' : '[BETA] : Space Management',
  // 'spinal-twin.ParentNodes' : '[BETA] : Parent Nodes',
  'spinal-twin.SpaceConfiguration' : 'Configuration',
  'spinal-twin.ParentNodes' : 'Parent Nodes',
};
